### ISSUE TITLE
Can't enable Title display for other display modes than Teaser

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/title_display#1]
After enabling *Title display* successfully for the Teaser display mode on the Post content type configuration form, I customized two more display modes (*Full* and *Print*) on the "Manage Displays" page. Unfortunately, none of these customized display modes appears on the content type config form (even not after clearing caches), so the functionality can't be enabled for other content types than Teaser.

**Comment by olafgrabienski** [comment]
Not sure if related: when enabling a display mode via the "Customize" button on the "Manage display" page, I get the following message:

> Notice: Undefined index: default in _field_ui_add_default_view_mode_settings() (line 1485 of /my-path-to/core/modules/field_ui/field_ui.admin.inc).

**Comment by quicksketch** [comment]
Thanks for trying this module @olafgrabienski! I found that there was an issue with out-of-box display modes. While adding a new display mode showed a checkbox for enabling, the out-of-box disabled display modes would not show a checkbox even if they were enabled on that content type.

The PR at https://github.com/backdrop-contrib/title_display/pull/2 should fix this issue. I'll make a new release shortly.

**Comment by olafgrabienski** [comment]
Thanks for the fix @quicksketch ! Updating to the last release [1.x-1.2.1] fixed the issue for me.
